### ISSUE TITLE
애드온 입력창 자체에서 한글입력이 안되는경우

### ISSUE THREAD

**Issue by claudianus** [kirumon/KoreanIME#1]
어떻게해야 할까요?

**Comment by kirumon** [comment]
탭키를 눌러 한글 입력 모드로 전환했어도 한글 입력이 안된다는 말씀인가요?

**Comment by claudianus** [comment]
> 탭키를 눌러 한글 입력 모드로 전환했어도 한글 입력이 안된다는 말씀인가요?

탭을 눌러줘야하는군요! 잘됩니다 감사합니다.
